### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-inflammation#415]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected => @katrinleinweber went through all non-`supp`
lementary material
- [x] Challenge / exercise solutions are correct => #424  & #427
- [x] Call out boxes (exercises, discussions, tips, etc.) render correctly => @katrinleinweber checked for left-over `>`, `{:`, etc. in HTML & **found none**
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete => 86a5148 
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent) => done in #395, #398, #408 & others
- [x] Some Instructor notes are provided => [_extras/guide.md](https://github.com/swcarpentry/r-novice-inflammation/blob/master/_extras/guide.md)
- [x] Lesson links work as expected => 001ca45 repairs 1 broken link

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by diyadas** [comment]
We've discussed and we'd like to be included in the June lesson release. Will work through the checklist.

**Comment by katrinleinweber** [comment]
I'll also run `make lesson-check-all` and remove all warnings.

**Comment by katrinleinweber** [comment]
Regarding "File structure is clean": Can we remove the whole boilerplate folder?

**Comment by fmichonneau** [comment]
it's not needed by the template. Depending on the number of lessons that will be involved in the release, I'm planning to migrate some/all to using remote themes. With this approach, none of the template files would be part of the repository anymore and updates to the template will happen with every push.

**Comment by katrinleinweber** [comment]
Sounds good! #418 will remove those files for now and in case any later merge conflicts appear because of that, I take responsibility to for resolving them.

**Comment by diyadas** [comment]
Short of a single diagram (that wasn't included in past lesson releases), I think we've addressed everything! 🎉 

There are a lot of issues tagged with the June lesson release milestone, but we classify them as enhancements. If they are resolved with PRs by then, they will be included. (I personally find it useful to keep some low-hanging fruit for newcomers.)

**Comment by katrinleinweber** [comment]
Agreed :-)

**Comment by ErinBecker** [comment]
Awesome work @swcarpentry/r-novice-inflammation-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3265218

**Comment by katrinleinweber** [comment]
Huge thanks to @fmichonneau & @ErinBecker for organising this and to @diyadas for the awesome teamwork :-)
